<?php

namespace QuidditchBundle\Repository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByEquipeMatch($data)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->Where('e.nom == :equipe1')
                ->setParameter('equipe1', $data['equipe1'])
            ->andWhere('e.nom == :equipe2')
            ->setParameter('equipe2', $data['equipe2'])
        ;

        return  $qb->getQuery()->getResult();
    }
}
