<?php

namespace QuidditchBundle\Repository;
use QuidditchBundle\Entity\Equipe;
use QuidditchBundle\Entity\Joueur;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends \Doctrine\ORM\EntityRepository
{

}

