<?php

namespace ImmoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchRepository extends EntityRepository
{
    public function findByMySearch($data)
    {
        $qb = $this->createQueryBuilder('m');
        if ($data['equipe1']) {
            $qb->andWhere('b.titre LIKE :maRecherche')
            ->orWhere('b.description LIKE :maRecherche')
            ->setParameter('maRecherche', '%' . $data['maRecherche'] . '%');
        }
        $qb->andWhere('b.superficie >= :superficie')
             ->setParameter('superficie', $data['superficie'])
        ->andWhere('b.prix <= :prix')
            ->setParameter('prix', $data['prix'])
            ->orderBy('b.ville', 'ASC')
        ;

         return  $qb->getQuery()->getResult();
    }
}
